services:
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: tvshowlogger-api
    ports:
      - "8080:8080"
    env_file: .env.docker
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;Database=solarwatch;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    container_name: tvshowlogger-postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: .env.docker
    # environment:
    #   POSTGRES_DB: ${DB_NAME:-tvshowlogger}
    #   POSTGRES_USER: ${DB_USER}
    #   POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
